# -*- coding: utf-8 -*-
"""ML_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13f4_zw7fg-ARlDwR_PT_GX9lmwFlXt7V
"""

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

data = load_breast_cancer()
X  = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression(max_iter=10)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)

import numpy as np

coefficients = model.coef_[0]
important_index = np.argmax(abs(coefficients))
important_feature = data.feature_names[important_index]

print("Most important feature:", important_feature)